# Generated by Django 4.2.1 on 2023-05-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_details_delete_patientdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('doctorid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('secondname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=8)),
                ('specializations', models.CharField(max_length=100)),
                ('specialized_field', models.CharField(max_length=100)),
                ('clinic_address', models.CharField(max_length=300)),
                ('role', models.CharField(default='doctor', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('patientid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('secondname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=8)),
                ('role', models.CharField(default='patient', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User_Details',
        ),
        migrations.RenameField(
            model_name='patientfeedback',
            old_name='p_id',
            new_name='patientid',
        ),
        migrations.RemoveField(
            model_name='patientappointment',
            name='mail1',
        ),
        migrations.RemoveField(
            model_name='patientappointment',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='patientappointment',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='patientfeedback',
            name='doctor',
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='doc_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='patient_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='doc_id',
            field=models.IntegerField(null=True),
        ),
    ]
