# Generated by Django 4.2.1 on 2023-05-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_doctordetails_patientdetails_delete_user_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='appointment_status',
            field=models.CharField(default='accepted', max_length=40),
        ),
    ]
